import sbtscalaxb.ScalaxbPlugin.*
import scoverage.ScoverageKeys

val appName         = "transit-movements-trader-manage-documents"
val silencerVersion = "1.7.9"

lazy val P4 = config("p4") extend Compile
lazy val P5 = config("p5") extend Compile

lazy val microservice = Project(appName, file("."))
  .enablePlugins(play.sbt.PlayScala, SbtAutoBuildPlugin, SbtDistributablesPlugin, ScalaxbPlugin)
  .disablePlugins(JUnitXmlReportPlugin)
  .settings(
    majorVersion := 0,
    libraryDependencies ++= AppDependencies.compile ++ AppDependencies.test,
    dependencyOverrides ++= AppDependencies.overrides,
    ThisBuild / scalafmtOnCompile := true,
    ScoverageKeys.coverageExcludedFiles := "<empty>;Reverse.*;.*handlers.*;.*repositories.*;" +
      ".*BuildInfo.*;.*javascript.*;.*Routes.*;.*GuiceInjector;" +
      ".*ControllerConfiguration;.*LanguageSwitchController",
    ScoverageKeys.coverageExcludedPackages := ".*views.xml.*",
    ScoverageKeys.coverageMinimumStmtTotal := 75,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true
  )
  .settings(scalaVersion := "2.12.15")
  .settings(resolvers += Resolver.jcenterRepo)
  .settings(inConfig(Test)(testSettings) *)
  .settings(PlayKeys.playDefaultPort := 9484)
  .settings(
    // silence all warnings on autogenerated files
    scalacOptions += "-P:silencer:pathFilters=target/.*",
    // Make sure you only exclude warnings for the project directories, i.e. make builds reproducible
    scalacOptions += s"-P:silencer:sourceRoots=${baseDirectory.value.getCanonicalPath}",
    libraryDependencies ++= Seq(
      compilerPlugin("com.github.ghik" % "silencer-plugin" % silencerVersion cross CrossVersion.full),
      "com.github.ghik" % "silencer-lib" % silencerVersion % Provided cross CrossVersion.full
    )
  )
  .settings(customScalaxbSettings: _*)

lazy val testSettings: Seq[Def.Setting[?]] = Seq(
  fork := true,
  javaOptions ++= Seq(
    "-Dconfig.resource=test.application.conf",
    "-Dlogger.resource=logback-test.xml"
  )
)

def customScalaxbSettings: Seq[Def.Setting[_]] =
  inConfig(P4)(baseScalaxbSettings ++ inTask(scalaxb)(customScalaxbSettingsFor("p4"))) ++
    inConfig(P5)(baseScalaxbSettings ++ inTask(scalaxb)(customScalaxbSettingsFor("p5"))) ++
    Seq(
      Compile / sourceGenerators += (P4 / scalaxb).taskValue,
      Compile / sourceGenerators += (P5 / scalaxb).taskValue
    )

def customScalaxbSettingsFor(base: String): Seq[Def.Setting[_]] = Seq(
  sourceManaged := (Compile / sourceManaged).value,
  scalaxbXsdSource := new File(s"./conf/xsd/$base"),
  scalaxbDispatchVersion := "1.1.3",
  scalaxbPackageName := s"generated.$base"
)
